export const state = {
  theme: "dark",
  paletteId: "default",
  customPaletteHex: "#B25B33",
  isPaletteModalOpen: false,
  isProfileModalOpen: false,
  feedback: null,
  viewer: null,
  reportedTopicIds: [],
  reportedMessageIds: [],
  selectedTopicId: null,
  rankingScope: "global",
  globalRankingIndex: 0,
  topicRankingIndex: 0,
  refreshCount: 0,
  mobileView: "browse",
  currentUserId: "u1",
  activeConnectedUserId: null,
  topics: [],
  users: []
};
