export const state = {
  theme: "dark",
  paletteId: "default",
  customPaletteHex: "#B25B33",
  isPaletteModalOpen: false,
  isProfileModalOpen: false,
  isSettingsModalOpen: false,
  settingsDeleteConfirming: false,
  settingsUpdatePending: false,
  isFriendRequestsPanelOpen: false,
  friendRequestsTab: "incoming",
  friendRequestsLimits: {
    incoming: 10,
    outgoing: 10
  },
  isNotificationsPanelOpen: false,
  isAdminPanelOpen: false,
  adminDashboard: null,
  reportModal: { isOpen: false, entityType: null, entityId: null },
  adminConfirmAction: null,
  feedback: null,
  viewer: null,
  reportedTopicIds: [],
  reportedMessageIds: [],
  unreadTopicIds: [],
  followedTopicIds: [],
  friendships: {
    incoming: [],
    outgoing: [],
    friends: []
  },
  notifications: [],
  notifiedMessageIds: [],
  webNotificationsPermission: "default",
  rankings: null,
  selectedTopicId: null,
  rankingScope: "global",
  globalRankingIndex: 0,
  topicRankingIndex: 0,
  refreshCount: 0,
  mobileView: "browse",
  currentUserId: "u1",
  activeConnectedUserId: null,
  publicProfileUserId: null,
  topics: [],
  users: []
};
