const REQUIRED_DOM_KEYS = [
  "shell",
  "workspace",
  "topbar",
  "themeToggle",
  "refreshButton",
  "topicsRefreshButton",
  "shareTopicButton",
  "shareTopicModalBackdrop",
  "shareTopicModal",
  "closeShareTopicModalButton",
  "sharePreviewTitle",
  "sharePreviewExcerpt",
  "sharePreviewAuthor",
  "sharePreviewNickname",
  "sharePreviewComments",
  "sharePreviewAvatar",
  "sharePreviewAvatarFallback",
  "shareTopicUrl",
  "nativeShareTopicButton",
  "copyTopicLinkButton",
  "downloadTopicCardButton",
  "topicShareCanvas",
  "chatTitle",
  "messageForm",
  "rankingPrev",
  "rankingCurrent",
  "rankingNext",
  "drawerRankingPrev",
  "drawerRankingCurrent",
  "drawerRankingNext",
  "openRightDrawer",
  "drawerBackdrop",
  "profileButton",
  "backToTopics",
  "authTools",
  "friendRequestsButton",
  "notificationsButton",
  "authButton",
  "storeButton",
  "paletteButton",
  "themeToggleDesktopSlot",
  "themeToggleMobileSlot",
  "themeToggleDrawerSlot",
  "mobileTopbarMenu",
  "mobileDrawerPanels",
  "paletteModalBackdrop",
  "authModalBackdrop",
  "authModal",
  "authModalTitle",
  "closeAuthModalButton",
  "authGoogleSection",
  "authGoogleButton",
  "authTurnstile",
  "authTurnstileToken",
  "authStatus",
  "authPasswordForm",
  "authLoginModeButton",
  "authRegisterModeButton",
  "authNicknameInput",
  "authEmailField",
  "authEmailInput",
  "authAgeInput",
  "authBirthDay",
  "authBirthMonth",
  "authBirthYear",
  "authPasswordField",
  "authPasswordInput",
  "authPasswordConfirmField",
  "authPasswordConfirmInput",
  "authRecoveryButton",
  "authCodeInput",
  "authCodeBoxes",
  "authCodeHint",
  "authTermsField",
  "authTermsInput",
  "authBackButton",
  "authPasswordButton",
  "authSendCodeAgainButton",
  "profileModalBackdrop",
  "publicProfileModalBackdrop",
  "adminPanelButton",
  "adminModalBackdrop",
  "adminModal",
  "adminPanelBody",
  "closeAdminModalButton",
  "reportModalBackdrop",
  "reportModal",
  "reportModalTitle",
  "closeReportModalButton",
  "reportReasonForm",
  "reportReasonOptions",
  "reportOtherReasonField",
  "reportOtherReasonInput",
  "reportModalSubmitButton",
  "paletteModal",
  "profileModal",
  "publicProfileModal",
  "publicProfileName",
  "publicProfileUsername",
  "publicProfileGuestNotice",
  "publicProfileCopyLinkButton",
  "publicProfileAvatar",
  "publicProfileMeta",
  "publicProfileDescription",
  "publicProfileJoinedAt",
  "publicProfileRecentCafes",
  "publicProfileSocial",
  "publicProfileScrollIndicator",
  "publicProfileReportButton",
  "publicProfileBlockActions",
  "publicProfileBlockButton",
  "publicProfileBlockConfirm",
  "publicProfileBlockPrompt",
  "publicProfileBlockChoice",
  "publicProfileHideContentToggle",
  "publicProfileBlockCancelButton",
  "publicProfileBlockConfirmButton",
  "closePublicProfileModalButton",
  "profileDisplayName",
  "profileAvatarPreview",
  "profileNameSection",
  "profileNameEditButton",
  "profileNameInput",
  "profileNameFeedback",
  "profileUsernameSection",
  "profileUsernameInput",
  "profileUsernameFeedback",
  "profileAvatarSection",
  "profileJoinedAtSection",
  "profileJoinedAtText",
  "profileJoinedAtVisibilityButton",
  "profileDescriptionSection",
  "profileDescriptionEditButton",
  "profileDescriptionVisibilityButton",
  "profileDescriptionInput",
  "profileSocialSection",
  "profileSocialVisibilityButton",
  "socialWhatsappInput",
  "socialInstagramInput",
  "socialTiktokInput",
  "socialFacebookInput",
  "socialTwitterInput",
  "socialDiscordInput",
  "socialWhatsappIcon",
  "socialInstagramIcon",
  "socialTiktokIcon",
  "socialFacebookIcon",
  "socialTwitterIcon",
  "socialDiscordIcon",
  "profileAvatarInput",
  "profileAvatarPickButton",
  "profileAvatarCropBackdrop",
  "profileAvatarCropModal",
  "profileAvatarCropFrame",
  "profileAvatarCropImage",
  "profileAvatarCropZoom",
  "profileAvatarCropCancelButton",
  "profileAvatarCropApplyButton",
  "profileLinkGoogleButton",
  "skipProfileButton",
  "saveProfileButton",
  "closeProfileModalButton",
  "actionFeedback",
  "friendRequestsPanel",
  "notificationToasts",
  "paletteOptionGrid",
  "closePaletteModalButton",
  "chatTopicName",
  "chatTopicDescription",
  "rankingsTitle",
  "rankingScopeTabs",
  "rankingModeList",
  "rankingsGlyph",
  "rankingScopeButton",
  "rankingScopeIcon",
  "rankingsEmpty",
  "rankingsBody",
  "rankingsPanel",
  "rankingCarousel",
  "drawerRankingsTitle",
  "drawerRankingScopeTabs",
  "drawerGlobalScopePrev",
  "drawerGlobalScopeNext",
  "drawerTopicScopePrev",
  "drawerTopicScopeNext",
  "drawerRankingsGlyph",
  "drawerRankingsEmpty",
  "drawerRankingsBody",
  "drawerRankingsSection",
  "drawerUsersSection",
  "drawerRankingSwitch",
  "topicTitleInput",
  "messageInput",
  "messageStream",
  "topicList",
  "createTopicButton",
  "leftDrawerTopics",
  "userList",
  "drawerUserList",
  "rankingList",
  "drawerRankingList",
  "drawerGlobalRankingList",
  "drawerTopicRankingList",
  "leftDrawer",
  "rightDrawer"
];

const DOM_IDS = [
  "themeToggle",
  "refreshButton",
  "topicsRefreshButton",
  "shareTopicButton",
  "shareTopicModalBackdrop",
  "shareTopicModal",
  "closeShareTopicModalButton",
  "sharePreviewTitle",
  "sharePreviewExcerpt",
  "sharePreviewAuthor",
  "sharePreviewNickname",
  "sharePreviewComments",
  "sharePreviewAvatar",
  "sharePreviewAvatarFallback",
  "shareTopicUrl",
  "nativeShareTopicButton",
  "copyTopicLinkButton",
  "downloadTopicCardButton",
  "topicShareCanvas",
  "reportTopicButton",
  "chatTitle",
  "messageForm",
  "rankingPrev",
  "rankingCurrent",
  "rankingNext",
  "drawerRankingPrev",
  "drawerRankingCurrent",
  "drawerRankingNext",
  "drawerGlobalRankingPrev",
  "drawerGlobalRankingCurrent",
  "drawerGlobalRankingNext",
  "drawerTopicRankingHeader",
  "drawerGlobalRankingHeader",
  "drawerGlobalRankingPanel",
  "drawerTopicRankingPanel",
  "openRightDrawer",
  "drawerBackdrop",
  "profileButton",
  "backToTopics",
  "authTools",
  "friendRequestsButton",
  "notificationsButton",
  "authButton",
  "storeButton",
  "paletteButton",
  "adminPanelButton",
  "adminModalBackdrop",
  "adminModal",
  "adminPanelBody",
  "closeAdminModalButton",
  "themeToggleDesktopSlot",
  "themeToggleMobileSlot",
  "themeToggleDrawerSlot",
  "mobileTopbarMenu",
  "mobileDrawerPanels",
  "paletteModalBackdrop",
  "authModalBackdrop",
  "authModal",
  "authModalTitle",
  "closeAuthModalButton",
  "authGoogleSection",
  "authGoogleButton",
  "authTurnstile",
  "authTurnstileToken",
  "authStatus",
  "authPasswordForm",
  "authLoginModeButton",
  "authRegisterModeButton",
  "authNicknameInput",
  "authEmailField",
  "authEmailInput",
  "authAgeInput",
  "authBirthDay",
  "authBirthMonth",
  "authBirthYear",
  "authPasswordField",
  "authPasswordInput",
  "authPasswordConfirmField",
  "authPasswordConfirmInput",
  "authRecoveryButton",
  "authCodeInput",
  "authCodeBoxes",
  "authCodeHint",
  "authTermsField",
  "authTermsInput",
  "authBackButton",
  "authPasswordButton",
  "authSendCodeAgainButton",
  "profileModalBackdrop",
  "publicProfileModalBackdrop",
  "adminPanelButton",
  "adminModalBackdrop",
  "adminModal",
  "adminPanelBody",
  "closeAdminModalButton",
  "reportModalBackdrop",
  "reportModal",
  "reportModalTitle",
  "closeReportModalButton",
  "reportReasonForm",
  "reportReasonOptions",
  "reportOtherReasonField",
  "reportOtherReasonInput",
  "reportModalSubmitButton",
  "paletteModal",
  "profileModal",
  "publicProfileModal",
  "publicProfileName",
  "publicProfileUsername",
  "publicProfileGuestNotice",
  "publicProfileCopyLinkButton",
  "publicProfileAvatar",
  "publicProfileMeta",
  "publicProfileDescription",
  "publicProfileJoinedAt",
  "publicProfileRecentCafes",
  "publicProfileSocial",
  "publicProfileReportButton",
  "closePublicProfileModalButton",
  "profileDisplayName",
  "profileAvatarPreview",
  "profileNameSection",
  "profileNameEditButton",
  "profileNameInput",
  "profileNameFeedback",
  "profileUsernameSection",
  "profileUsernameInput",
  "profileUsernameFeedback",
  "profileAvatarSection",
  "profileJoinedAtSection",
  "profileJoinedAtText",
  "profileJoinedAtVisibilityButton",
  "profileDescriptionSection",
  "profileDescriptionEditButton",
  "profileDescriptionVisibilityButton",
  "profileDescriptionInput",
  "profileSocialSection",
  "profileSocialVisibilityButton",
  "socialWhatsappInput",
  "socialInstagramInput",
  "socialTiktokInput",
  "socialFacebookInput",
  "socialTwitterInput",
  "socialDiscordInput",
  "socialWhatsappIcon",
  "socialInstagramIcon",
  "socialTiktokIcon",
  "socialFacebookIcon",
  "socialTwitterIcon",
  "socialDiscordIcon",
  "profileAvatarInput",
  "profileAvatarPickButton",
  "profileAvatarCropBackdrop",
  "profileAvatarCropModal",
  "profileAvatarCropFrame",
  "profileAvatarCropImage",
  "profileAvatarCropZoom",
  "profileAvatarCropCancelButton",
  "profileAvatarCropApplyButton",
  "profileLinkGoogleButton",
  "skipProfileButton",
  "saveProfileButton",
  "closeProfileModalButton",
  "settingsButton",
  "settingsModalBackdrop",
  "settingsModal",
  "closeSettingsModalButton",
  "settingsLikesAnonymousToggle",
  "settingsProfileIndexableToggle",
  "settingsFilterProfanityToggle",
  "settingsFriendsOnlyToggle",
  "settingsBlockedUsers",
  "settingsDeleteAccountButton",
  "settingsDeleteConfirmRow",
  "settingsDeleteCancelButton",
  "settingsDeleteConfirmButton",
  "actionFeedback",
  "friendRequestsPanel",
  "notificationToasts",
  "paletteOptionGrid",
  "closePaletteModalButton",
  "chatTopicName",
  "chatTopicDescription",
  "rankingsTitle",
  "rankingScopeTabs",
  "rankingModeList",
  "rankingsGlyph",
  "rankingScopeButton",
  "rankingScopeIcon",
  "rankingsEmpty",
  "drawerRankingsTitle",
  "drawerRankingScopeTabs",
  "drawerGlobalScopePrev",
  "drawerGlobalScopeNext",
  "drawerTopicScopePrev",
  "drawerTopicScopeNext",
  "drawerRankingsGlyph",
  "drawerRankingsEmpty",
  "topicTitleInput",
  "messageInput",
  "messageStream",
  "topicList",
  "createTopicButton",
  "leftDrawerTopics",
  "userList",
  "drawerUserList",
  "rankingList",
  "drawerRankingList",
  "drawerGlobalRankingList",
  "drawerTopicRankingList",
  "leftDrawer",
  "rightDrawer"
];

export function cacheDom() {
  const baseCache = {
    shell: document.querySelector(".shell"),
    workspace: document.querySelector(".workspace"),
    topbar: document.querySelector(".topbar"),
    rankingsBody: document.querySelector(".panel__body--users-rankings .rankings-section"),
    drawerRankingsBody: document.querySelector(".panel__body--drawer-rankings"),
    drawerCloseButtons: Array.from(document.querySelectorAll("[data-close-drawer]"))
  };

  // Pre-populate with known IDs for performance
  DOM_IDS.forEach((id) => {
    baseCache[id] = document.getElementById(id);
  });

  const domProxy = new Proxy(baseCache, {
    get(target, prop) {
      if (target[prop] !== undefined) {
        return target[prop];
      }

      // If not in cache, try to find it by ID
      if (typeof prop === "string") {
        const element = document.getElementById(prop);
        if (element) {
          target[prop] = element;
          return element;
        }
      }

      return undefined;
    }
  });

  domProxy.rankingsPanel = domProxy.rankingsTitle?.closest(".panel--users-rankings") ?? null;
  domProxy.rankingCarousel = domProxy.rankingPrev?.closest(".ranking-carousel") ?? null;
  domProxy.drawerRankingsSection = domProxy.drawerRankingList?.closest(".drawer__section") ?? null;
  domProxy.drawerUsersSection = domProxy.drawerUserList?.closest(".drawer__section") ?? null;
  domProxy.drawerRankingSwitch =
    domProxy.drawerRankingPrev?.closest(".drawer-ranking__switch") ?? null;
  domProxy.drawerGlobalRankingSwitch =
    domProxy.drawerGlobalRankingPrev?.closest(".drawer-ranking__switch") ?? null;
  domProxy.drawerTopicRankingSwitch =
    domProxy.drawerRankingPrev?.closest(".drawer-ranking__switch") ?? null;
  domProxy.composerSubmitButton =
    domProxy.messageForm?.querySelector('button[type="submit"]') ?? null;

  assertRequiredDom(domProxy);
  return domProxy;
}

function assertRequiredDom(cached) {
  const missing = REQUIRED_DOM_KEYS.filter((key) => !cached[key]);
  if (!cached.drawerCloseButtons.length) {
    missing.push("drawerCloseButtons");
  }

  if (missing.length) {
    throw new Error(`Missing required DOM nodes: ${missing.join(", ")}`);
  }
}
